### ISSUE TITLE
Load tables from localStorage

### ISSUE THREAD

**Issue by kwheelan** [CityOfDetroit/Departmental-Budget-Request-Form#18]
- [x] After reading in Excel sheet, tables should be loaded on the page from localStorage (using the Baseline and Supplemental objects) instead of from the JSON files. This will capture edits when the user returns to a page with a table.
 - [x] Load funds list from storage
 - [x] add an init function for Baseline to automatically read in all funds
 - [x] Add table function to hide columns
 - [x] Add capacity to hide columns that aren't named in helpers file
 - [x] Unify all data storage to be JSON for now
 - [x] Save table correctly by removing the edit column
 - [x] Load 'service' from stored data

**Comment by kwheelan** [comment]
Will define visible columns for OT, Revenue, and Nonpersonnel in #14, #4 ,and #15
