### ISSUE TITLE
Questions for Janani/Noah

### ISSUE THREAD

**Issue by kwheelan** [CityOfDetroit/Departmental-Budget-Request-Form#39]
## Questions on detail sheet

Addressed in comment below

## Confirmation about app

- Replaced string with columns for approp and cc for OT
- Moved contract end date and amount remaining to CPA# tooltip

## Additional features?

 - Allow table row deletions?
 - Add comment column for all tables?

**Comment by kwheelan** [comment]
## Revenue Feedback

 - remove FY24 rev estimates -- only need most recent (called latest forecast)
 - Change Department Request Total --> Departmental Estimated Total
 - Change Department Request Notes --> Departmental Estimate Notes

**Comment by kwheelan** [comment]
## Questions for Noah 7/24/24

### Detail sheet

- Personnel: what happens between S and U? General increase?
     - Yes, will add a column for *average* projected sal/wag FY26
- OT: collapse to one row or not worth it?
     - No, adjust on my end (#42)
- Revenue: delete col T 
- Revenue: rename cols V and W
     - Edit on my end too (#58) 

### Questions

- What format for excel output?
     - Fix if time (#32) 
- Where to find target?
      - #55
      - #56

**Comment by kwheelan** [comment]
Confirm that total and target refer to total expenditure and not total expenditure net of fund revenues

--> confirmed

**Comment by katrina-cityofdetroit** [comment]
What does CPA stand for? Contracting and Procurement Agreement?

**Comment by katrina-cityofdetroit** [comment]
Confirm: 
 - #71 
 - #72
     - Instead, retain FTE to 0 but also add instruction to mention in comment

**Comment by katrina-cityofdetroit** [comment]
- [ ] edit column on download -- show which rows were edited (#89 )
 - [ ] Make sure initiatives are downloaded and can be re-uploaded (#87 )
 - [ ] ~~Disable download block if over budget~~
 - [ ] ~~Allow download of excel throughout~~
 - [x] Disable most revenue edits
 - [ ] create job title dropdown for new position (#88 )
 - [ ] automatically add job code (#95 )
 - [ ] intranet.detroit.mi -- find location for page (#90 )
 - [ ] instructions on welcome page (#74)
 - [ ] confirm video format with Donnie for instructions (#62 )

**Comment by katrina-cityofdetroit** [comment]
Noah 9/9/2024:
(Deliverables moved to #83 )

- We need to include the job codes along with the job titles. There's no way you would've known this, but job titles are not unique and are often shared among different job codes, because of reasons. For example, there are two different job codes with the title "General Auto Mechanic," one code for DPW employees and one code for DDoT employees. They are covered by different unions and therefore have different pay ranges. So, we need to include the job code in there so that we can identify the proper pay range and/or benefits package.
- When entering a new job or new non-personnel item, I wasn't able to enter new Appropriations or Cost Centers. Every new fiscal year inevitably brings a few new approp or cc codes, so they'll need to be able to enter new ones that aren't part of the initial upload.
- I wasn't able to add new jobs because there was nothing in the Service drop-down menu. I know Services are still a work-in-progress, though.
- Also when entering a new job, they shouldn't be entering 'Expected fringe rate.' That's something we (Office of Budget) assign based on the Job Code (it's part of the Gold Book personnel data).
- At the end of the process, it wouldn't let me download the new Excel file; it kept telling me I was above baseline target, even though I brought it below

**Comment by katrina-cityofdetroit** [comment]
Newest feedback documented on #83
